[general]
# Template directories relative to CARGO_MANIFEST_DIR
dirs = ["src/templates"]

[[syntax]]
name = "java"
ext = "java"
escaper = "none"

[[syntax]]
name = "rs"
ext = "rs"
escaper = "none"
