#![allow(dead_code)]

// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

use jni::JNIEnv;
use jni::objects::JByteBuffer;
use jni::sys::*;
use uniffi::ffi::{ForeignBytes, RustBuffer};

/// Convert a Rust String to a JNI jstring.
pub fn rust_string_to_jni(env: &mut JNIEnv, s: &str) -> jstring {
    env.new_string(s)
        .expect("Failed to create Java string")
        .into_raw()
}

/// Convert a JNI jstring to a Rust String.
pub fn jni_to_rust_string(env: &mut JNIEnv, s: jstring) -> String {
    env.get_string(&unsafe { jni::objects::JString::from_raw(s) })
        .expect("Failed to read Java string")
        .into()
}

/// Convert a Direct ByteBuffer to a Rust Vec<u8>.
pub fn jni_bytebuffer_to_vec(env: &mut JNIEnv, buf: &JByteBuffer) -> Vec<u8> {
    let addr = env.get_direct_buffer_address(buf)
        .expect("Failed to get direct buffer address");
    let capacity = env.get_direct_buffer_capacity(buf)
        .expect("Failed to get direct buffer capacity");
    unsafe {
        std::slice::from_raw_parts(addr as *const u8, capacity).to_vec()
    }
}

/// Convert a Rust Vec<u8> to a Direct ByteBuffer.
pub fn vec_to_jni_bytebuffer(env: &mut JNIEnv, data: &[u8]) -> jobject {
    let len = data.len();
    let ptr = data.as_ptr() as *mut u8;
    let buf = unsafe { env.new_direct_byte_buffer(ptr, len) }
        .expect("Failed to create direct byte buffer");
    buf.into_raw()
}

/// Convert a JNI ByteBuffer (jobject) to a UniFFI RustBuffer.
///
/// Reads the data from the Java Direct ByteBuffer and copies it into
/// a new RustBuffer owned by Rust.
pub unsafe fn jni_bytebuffer_to_rustbuffer(
    env: &mut JNIEnv,
    buf: jobject,
) -> RustBuffer {
    let jbuf = JByteBuffer::from_raw(buf);
    let addr = env.get_direct_buffer_address(&jbuf)
        .expect("Failed to get direct buffer address");
    let capacity = env.get_direct_buffer_capacity(&jbuf)
        .expect("Failed to get direct buffer capacity");
    let data = std::slice::from_raw_parts(addr as *const u8, capacity);
    RustBuffer::from_vec(data.to_vec())
}

/// Convert a JNI ByteBuffer (jobject) to a UniFFI ForeignBytes.
///
/// This creates a ForeignBytes struct that borrows from the JNI direct buffer.
/// The caller must ensure the JNI buffer remains alive for the duration of the call.
pub unsafe fn jni_bytebuffer_to_foreignbytes(
    env: &mut JNIEnv,
    buf: jobject,
) -> ForeignBytes {
    let jbuf = JByteBuffer::from_raw(buf);
    let addr = env.get_direct_buffer_address(&jbuf)
        .expect("Failed to get direct buffer address");
    let capacity = env.get_direct_buffer_capacity(&jbuf)
        .expect("Failed to get direct buffer capacity");
    ForeignBytes::from_raw_parts(addr as *const u8, capacity as i32)
}

/// Convert a UniFFI RustBuffer into a JNI Direct ByteBuffer (jobject).
///
/// Copies the data into a new Java-managed Direct ByteBuffer,
/// then frees the RustBuffer.
pub unsafe fn rustbuffer_to_jni_bytebuffer(
    env: &mut JNIEnv,
    rb: RustBuffer,
) -> jobject {
    let len = rb.len();
    // Use data_pointer() which gives *const u8
    let data_ptr = rb.data_pointer() as *mut u8;
    let buf = env.new_direct_byte_buffer(data_ptr, len)
        .expect("Failed to create direct byte buffer");
    let result = buf.into_raw();
    // Free the RustBuffer data
    rb.destroy();
    result
}

/// Convert a JNI jlong to a *const T pointer.
pub unsafe fn jlong_to_ptr<T>(handle: jlong) -> *const T {
    handle as *const T
}

/// Convert a *const T pointer to a JNI jlong.
pub fn ptr_to_jlong<T>(ptr: *const T) -> jlong {
    ptr as jlong
}