// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

mod jni_types;
mod jni_bridge;
{% if has_callbacks %}
mod jni_callback;
{% endif %}

#[no_mangle]
#[allow(unused_variables)]
pub extern "system" fn JNI_OnLoad(
    vm: jni::JavaVM,
    _reserved: *mut std::ffi::c_void,
) -> jni::sys::jint {
    {% if has_callbacks %}
    // Store JavaVM reference for callback support
    // TODO: initialize callback infrastructure
    {% endif %}
    jni::sys::JNI_VERSION_1_8
}

