//! Rust JNI glue code generation module.
//!
//! This module generates the Rust JNI glue crate that bridges
//! between Java native methods and UniFFI FFI functions.

use anyhow::Result;
use camino::Utf8Path;
use fs_err as fs;

use crate::pipeline::nodes::*;

mod jni_func;
mod jni_types;
mod callback_gen;
mod cargo_toml;

/// Generate Rust JNI glue code from the Java IR root node.
pub fn generate_rust_glue(
    root: &Root,
    out_dir: &Utf8Path,
    crate_filter: Option<&str>,
) -> Result<()> {
    fs::create_dir_all(out_dir)?;

    let glue_crate_name = "uniffi-jni-glue";
    let cargo_toml_path = out_dir.join("Cargo.toml");
    let src_dir = out_dir.join("src");
    fs::create_dir_all(&src_dir)?;

    // Generate Cargo.toml
    let cargo_toml = cargo_toml::generate_cargo_toml(glue_crate_name, root);
    fs::write(&cargo_toml_path, cargo_toml)?;

    // Generate lib.rs
    let lib_rs = generate_lib_rs(root, crate_filter)?;
    fs::write(src_dir.join("lib.rs"), lib_rs)?;

    // Generate jni_bridge.rs
    let jni_bridge = generate_jni_bridge(root, crate_filter)?;
    fs::write(src_dir.join("jni_bridge.rs"), jni_bridge)?;

    // Generate jni_types.rs
    let jni_types_rs = jni_types::generate_jni_types();
    fs::write(src_dir.join("jni_types.rs"), jni_types_rs)?;

    // Generate jni_callback.rs
    let jni_callback = callback_gen::generate_jni_callback(root, crate_filter)?;
    fs::write(src_dir.join("jni_callback.rs"), jni_callback)?;

    println!("Generated Rust glue crate at: {}", out_dir);

    Ok(())
}

fn generate_lib_rs(root: &Root, crate_filter: Option<&str>) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.\n\n");
    out.push_str("mod jni_types;\n");
    out.push_str("mod jni_bridge;\n");
    out.push_str("mod jni_callback;\n\n");

    // Check for callback interfaces
    let has_callbacks = root.modules.values().any(|m| {
        if let Some(filter) = crate_filter {
            if m.crate_name != filter {
                return false;
            }
        }
        m.has_callback_interface
    });

    out.push_str("#[no_mangle]\n");
    out.push_str("pub extern \"system\" fn JNI_OnLoad(\n");
    out.push_str("    vm: jni::JavaVM,\n");
    out.push_str("    _reserved: *mut std::ffi::c_void,\n");
    out.push_str(") -> jni::sys::jint {\n");
    out.push_str("    jni::sys::JNI_VERSION_1_8\n");
    out.push_str("}\n");

    Ok(out)
}

fn generate_jni_bridge(root: &Root, crate_filter: Option<&str>) -> Result<String> {
    let mut out = String::new();
    out.push_str("// Auto-generated JNI bridge functions. DO NOT EDIT.\n\n");
    out.push_str("use jni::JNIEnv;\n");
    out.push_str("use jni::objects::JClass;\n");
    out.push_str("use jni::sys::*;\n\n");
    out.push_str("use crate::jni_types::*;\n\n");

    for module in root.modules.values() {
        if let Some(filter) = crate_filter {
            if module.crate_name != filter {
                continue;
            }
        }

        for ffi in &module.ffi_definitions {
            if let FfiDefinition::RustFunction(func) = ffi {
                out.push_str(&format!("#[no_mangle]\n"));
                out.push_str(&format!(
                    "pub extern \"system\" fn {} (\n",
                    func.jni_name
                ));
                out.push_str("    _env: JNIEnv,\n");
                out.push_str("    _class: JClass,\n");
                out.push_str(") {\n");
                out.push_str(&format!(
                    "    // TODO: call uniffi FFI function: {}\n",
                    func.name
                ));
                out.push_str("}\n\n");
            }
        }
    }

    Ok(out)
}
