// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.


/**
 * Interface for FFI type converters.
 *
 * Each UniFFI type has an associated {@code FfiConverter} that knows how to:
 * <ul>
 *   <li>{@link #lift} — convert an FFI value to a Java value</li>
 *   <li>{@link #lower} — convert a Java value to an FFI value</li>
 *   <li>{@link #read} — deserialize from a ByteBuffer</li>
 *   <li>{@link #write} — serialize into a ByteBuffer</li>
 *   <li>{@link #allocationSize} — calculate the buffer size needed for serialization</li>
 * </ul>
 *
 * @param <JavaType> the Java-side type
 * @param <FfiType>  the FFI (native) type (ByteBuffer, Long, Integer, etc.)
 */
public interface FfiConverter<JavaType, FfiType> {

    /**
     * Convert a low-level FFI value into a high-level Java value.
     */
    JavaType lift(FfiType ffiValue);

    /**
     * Convert a high-level Java value into a low-level FFI value.
     */
    FfiType lower(JavaType javaValue);

    /**
     * Read a Java-typed value from a ByteBuffer stream.
     */
    JavaType read(ByteBuffer buf);

    /**
     * Write a Java-typed value into a ByteBuffer stream.
     */
    void write(JavaType value, ByteBuffer buf);

    /**
     * Calculate the number of bytes needed to serialize this value
     * in the UniFFI wire format.
     */
    int allocationSize(JavaType value);
}
