// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.


/**
 * A thread-safe map that assigns unique numeric handles to Java objects.
 *
 * Handles are used by the native Rust code to reference Java-side callback
 * interface implementations and Rust objects that cross the FFI boundary.
 *
 * @param <T> the type of object stored in this map
 */
public static final class HandleMap<T> {

    private final ConcurrentHashMap<Long, T> map = new ConcurrentHashMap<>();
    private final AtomicLong nextHandle = new AtomicLong(1);

    /**
     * Insert an object and return its handle.
     */
    public long insert(T obj) {
        long handle = nextHandle.getAndIncrement();
        map.put(handle, obj);
        return handle;
    }

    /**
     * Get an object by handle, or {@code null} if not found.
     */
    public T get(long handle) {
        return map.get(handle);
    }

    /**
     * Remove and return an object by handle, or {@code null} if not found.
     */
    public T remove(long handle) {
        return map.remove(handle);
    }

    /**
     * Insert a clone of the object referenced by the given handle.
     * Returns the new handle, or 0 if the original handle was not found.
     */
    public long cloneHandle(long handle) {
        T obj = map.get(handle);
        if (obj != null) {
            return insert(obj);
        }
        return 0;
    }

    /**
     * Returns the number of entries in the map.
     */
    public int size() {
        return map.size();
    }
}
