// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.


/**
 * Status codes and helpers for Rust FFI calls.
 *
 * UniFFI uses a {@code RustCallStatus} struct to propagate errors across
 * the FFI boundary. Each native function that can fail receives an extra
 * output parameter pointing to a {@code RustCallStatus}.
 */
public static final class Helpers {

    private Helpers() {} // utility class

    // --- RustCallStatus ---

    /**
     * Mirrors the Rust {@code uniffi::RustCallStatus} struct layout.
     */
    public static final class RustCallStatus {
        /** The call succeeded. */
        public static final byte SUCCESS = 0;
        /** The call returned an expected error. */
        public static final byte ERROR = 1;
        /** The call panicked or returned an unexpected error. */
        public static final byte UNEXPECTED_ERROR = 2;

        private byte code;
        private ByteBuffer errorBuf;

        public RustCallStatus() {
            this.code = SUCCESS;
        }

        public byte getCode() { return code; }
        public void setCode(byte code) { this.code = code; }

        public ByteBuffer getErrorBuf() { return errorBuf; }
        public void setErrorBuf(ByteBuffer errorBuf) { this.errorBuf = errorBuf; }

        /**
         * Returns true if the call succeeded (code == SUCCESS).
         */
        public boolean isSuccess() { return code == SUCCESS; }

        /**
         * Returns true if this status represents an error.
         */
        public boolean isError() { return code == ERROR || code == UNEXPECTED_ERROR; }
    }

    // --- Error helpers ---

    /**
     * Read a RustCallStatus struct from native memory at the given handle.
     */
    static RustCallStatus readRustCallStatus(long handle) {
        ByteBuffer buf = {{ name }}.directBufferFromHandle(handle, 8);
        RustCallStatus status = new RustCallStatus();
        status.code = buf.get();
        // skip padding (3 bytes)
        buf.position(4);
        int errorBufHandle = buf.getInt();
        if (errorBufHandle != 0) {
            // errorBufHandle points to a RustBuffer; read its contents
            ByteBuffer errorBuf = {{ name }}.directBufferFromHandle(errorBufHandle, 16);
            int capacity = errorBuf.getInt();
            int len = errorBuf.getInt();
            long dataPtr = errorBuf.getLong();
            if (dataPtr != 0 && len > 0) {
                ByteBuffer data = {{ name }}.directBufferFromHandle(dataPtr, len);
                status.errorBuf = data;
            }
        }
        return status;
    }

    /**
     * Throw the appropriate Java exception if the RustCallStatus indicates an error.
     */
    static void ensureSuccess(RustCallStatus status) throws {{ name }}Exception {
        if (status.code == RustCallStatus.UNEXPECTED_ERROR) {
            String msg = status.errorBuf != null
                ? RustBufferStream.readStringFromBuffer(status.errorBuf)
                : "Unexpected Rust error (panic)";
            throw new {{ name }}Exception(msg);
        }
    }
}
