// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

package {{ package_name }};

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

/**
 * Reads and writes typed values to/from a {@link ByteBuffer} using the UniFFI
 * wire format.
 *
 * All multi-byte values use BIG_ENDIAN byte order.
 * Strings are encoded as an i32 length prefix followed by UTF-8 bytes.
 * Sequences are encoded as an i32 length prefix followed by serialized items.
 */
public final class RustBufferStream {

    private final ByteBuffer buf;

    public RustBufferStream(ByteBuffer buf) {
        this.buf = buf.duplicate().order(ByteOrder.BIG_ENDIAN);
    }

    // --- Read primitives ---

    public byte readInt8() { return buf.get(); }
    public short readUInt8() { return (short) (buf.get() & 0xFF); }
    public short readInt16() { return buf.getShort(); }
    public int readUInt16() { return buf.getShort() & 0xFFFF; }
    public int readInt32() { return buf.getInt(); }
    public long readUInt32() { return buf.getInt() & 0xFFFF_FFFFL; }
    public long readInt64() { return buf.getLong(); }
    public long readUInt64() { return buf.getLong(); }
    public float readFloat32() { return buf.getFloat(); }
    public double readFloat64() { return buf.getDouble(); }

    public boolean readBoolean() {
        return readInt8() != 0;
    }

    public String readString() {
        int len = readInt32();
        if (len < 0) {
            throw new RuntimeException("Negative string length in buffer: " + len);
        }
        if (len == 0) return "";
        byte[] bytes = new byte[len];
        buf.get(bytes);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    public byte[] readBytes() {
        int len = readInt32();
        if (len < 0) {
            throw new RuntimeException("Negative byte array length in buffer: " + len);
        }
        if (len == 0) return new byte[0];
        byte[] bytes = new byte[len];
        buf.get(bytes);
        return bytes;
    }

    public long readHandle() {
        return readInt64();
    }

    // --- Write primitives ---

    public void writeInt8(byte v) { buf.put(v); }
    public void writeUInt8(short v) { buf.put((byte) (v & 0xFF)); }
    public void writeInt16(short v) { buf.putShort(v); }
    public void writeUInt16(int v) { buf.putShort((short) (v & 0xFFFF)); }
    public void writeInt32(int v) { buf.putInt(v); }
    public void writeUInt32(long v) { buf.putInt((int) (v & 0xFFFF_FFFFL)); }
    public void writeInt64(long v) { buf.putLong(v); }
    public void writeUInt64(long v) { buf.putLong(v); }
    public void writeFloat32(float v) { buf.putFloat(v); }
    public void writeFloat64(double v) { buf.putDouble(v); }

    public void writeBoolean(boolean v) {
        writeInt8((byte) (v ? 1 : 0));
    }

    public void writeString(String v) {
        if (v == null) v = "";
        byte[] bytes = v.getBytes(StandardCharsets.UTF_8);
        writeInt32(bytes.length);
        buf.put(bytes);
    }

    public void writeBytes(byte[] v) {
        if (v == null) {
            writeInt32(0);
            return;
        }
        writeInt32(v.length);
        buf.put(v);
    }

    public void writeHandle(long v) {
        writeInt64(v);
    }

    // --- Compound helpers ---

    /**
     * Returns the number of bytes remaining in this stream.
     */
    public int remaining() {
        return buf.remaining();
    }

    /**
     * Returns the underlying ByteBuffer (at its current position).
     */
    public ByteBuffer buffer() {
        return buf;
    }

    /**
     * Convenience: read a UTF-8 string from a standalone ByteBuffer.
     * The buffer must be positioned at the start of the string data.
     */
    public static String readStringFromBuffer(ByteBuffer buf) {
        if (buf == null || buf.remaining() == 0) return "";
        RustBufferStream stream = new RustBufferStream(buf);
        return stream.readString();
    }
}
