// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

package {{ package_name }};

import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.nio.charset.StandardCharsets;

/**
 * A buffer of bytes that is allocated and freed by Rust.
 *
 * RustBuffer is a thin wrapper around a direct {@link ByteBuffer} that
 * carries a native handle used to free the underlying Rust-allocated memory.
 * After reading the buffer contents, users must call {@link #close()} to
 * release the native memory.
 */
public final class RustBuffer implements AutoCloseable {

    private ByteBuffer buf;
    private long handle;

    private RustBuffer(ByteBuffer buf, long handle) {
        this.buf = buf;
        this.handle = handle;
        if (this.buf != null) {
            this.buf.order(ByteOrder.BIG_ENDIAN);
        }
    }

    /**
     * Returns the underlying direct ByteBuffer for reading.
     * The buffer uses BIG_ENDIAN byte order matching the UniFFI wire format.
     */
    public ByteBuffer asByteBuffer() {
        return buf;
    }

    /**
     * The length (number of readable bytes) of this buffer.
     */
    public int len() {
        return buf != null ? buf.remaining() : 0;
    }

    /**
     * Frees the native memory backing this buffer.
     * Safe to call multiple times.
     */
    @Override
    public void close() {
        if (handle != 0) {
            {{ name }}.nativeRustBufferFree(handle);
            handle = 0;
        }
        buf = null;
    }

    // --- Static factory methods used by the generated code ---

    /**
     * Wrap a native-allocated RustBuffer returned from a native method.
     *
     * @param handle  the native handle (address of the Rust-allocated buffer struct)
     * @param len     number of bytes to read from the buffer
     */
    static RustBuffer fromNative(long handle, int len) {
        // handle points to a Rust RustBuffer struct { capacity: u32, len: u32, data: *mut u8 }
        // We read the data pointer from the struct, then create a ByteBuffer view.
        // The native handle is used later to free the buffer.
        ByteBuffer buf = directBufferFromHandle(handle, len);
        return new RustBuffer(buf, handle);
    }

    /**
     * Allocate a new RustBuffer for sending data to Rust.
     * The caller fills the buffer, then passes it to a native method.
     */
    static RustBuffer alloc(int capacity) {
        ByteBuffer buf = ByteBuffer.allocateDirect(capacity);
        buf.order(ByteOrder.BIG_ENDIAN);
        return new RustBuffer(buf, 0);
    }

    /**
     * Allocate a RustBuffer containing a UTF-8 encoded string.
     */
    static RustBuffer allocFromString(String s) {
        byte[] bytes = s.getBytes(StandardCharsets.UTF_8);
        RustBuffer rb = alloc(bytes.length);
        rb.buf.put(bytes);
        rb.buf.flip();
        return rb;
    }

    /**
     * Allocate a RustBuffer containing raw bytes.
     */
    static RustBuffer allocFromBytes(byte[] bytes) {
        RustBuffer rb = alloc(bytes.length);
        rb.buf.put(bytes);
        rb.buf.flip();
        return rb;
    }

    // --- Native helpers ---

    private static native ByteBuffer directBufferFromHandle(long handle, int len);

    /**
     * Consume the buffer contents as a UTF-8 string, then free the native memory.
     */
    public String consumeIntoString() {
        if (buf == null) return "";
        byte[] bytes = new byte[buf.remaining()];
        buf.get(bytes);
        String result = new String(bytes, StandardCharsets.UTF_8);
        close();
        return result;
    }

    /**
     * Consume the buffer contents as a byte array, then free the native memory.
     */
    public byte[] consumeIntoBytes() {
        if (buf == null) return new byte[0];
        byte[] bytes = new byte[buf.remaining()];
        buf.get(bytes);
        close();
        return bytes;
    }

    // --- Static helpers for reading raw ByteBuffer data from JNI bridge ---

    /**
     * Read a UTF-8 string from a raw ByteBuffer returned by the JNI bridge.
     * The buffer contains raw UTF-8 bytes (no length prefix).
     * Does NOT free any native memory (the JNI bridge already freed it).
     */
    static String readStringFromByteBuffer(ByteBuffer buf) {
        if (buf == null || buf.remaining() == 0) return "";
        byte[] bytes = new byte[buf.remaining()];
        buf.get(bytes);
        return new String(bytes, StandardCharsets.UTF_8);
    }

    /**
     * Read a byte array from a raw ByteBuffer returned by the JNI bridge.
     * The buffer contains raw bytes (no length prefix).
     * Does NOT free any native memory (the JNI bridge already freed it).
     */
    static byte[] readBytesFromByteBuffer(ByteBuffer buf) {
        if (buf == null || buf.remaining() == 0) return new byte[0];
        byte[] bytes = new byte[buf.remaining()];
        buf.get(bytes);
        return bytes;
    }
}
