// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

package {{ package_name }};

{% for import in imports %}
import {{ import }};
{% endfor %}

/**
 * UniFFI bindings for {{ name }}.
 *
 * Generated from crate: {{ crate_name }}
 */
{% if docstring.is_some() %}
/** {{ docstring.as_ref().unwrap() }} */
{% endif %}
@SuppressWarnings({"unused", "deprecation"})
public final class {{ name }} {

    static {
        System.loadLibrary("{{ cdylib_name }}");
    }

    // ---------------------------------------------------------------
    // Native method declarations
    // ---------------------------------------------------------------

    {% for ffi in ffi_definitions %}
    {%- match ffi %}
    {%- when FfiDefinition::RustFunction(func) %}
    private static native {% match func.return_type %}{% when Some with (ret) %}{{ ret|ffi_type_java }}{% when None %}void{% endmatch %} {{ func.name }}(
        {%- for arg in func.arguments -%}
        {{ arg.ty|ffi_type_java }} {{ arg.name }}{% if !loop.last %}, {% endif %}
        {%- endfor -%}
    );
    {%- when FfiDefinition::CallbackFunction(cb) %}
    // Callback type: {{ cb.name }} (handled via JNI callback bridge)
    {%- endmatch %}
    {% endfor %}

    // Helper native methods
    private static native java.nio.ByteBuffer directBufferFromHandle(long handle, int len);
    private static native void nativeRustBufferFree(long handle);

    // ---------------------------------------------------------------
    // Shared utility classes
    // ---------------------------------------------------------------

    {% include "java/RustBuffer.java" %}

    {% include "java/RustBufferStream.java" %}

    {% include "java/HandleMap.java" %}

    {% include "java/FfiConverter.java" %}

    {% include "java/Helpers.java" %}

    // ---------------------------------------------------------------
    // Top-level functions
    // ---------------------------------------------------------------

    {% for func in functions %}
    {%- include "java/Function.java" %}
    {% endfor %}

    // ---------------------------------------------------------------
    // Type definitions
    // ---------------------------------------------------------------

    {% for td in type_definitions %}
    {%- match td %}
    {%- when TypeDefinition::Object(obj) %}
    {%- match obj.imp %}
    {%- when ObjectImpl::Struct %}
    {% include "java/Object.java" %}
    {%- when ObjectImpl::Trait %}
    {% include "java/Interface.java" %}
    {%- when ObjectImpl::CallbackTrait %}
    // CallbackTrait object: {{ obj.java_name }} (Rust-implemented trait)
    {% include "java/Interface.java" %}
    {%- endmatch %}
    {%- when TypeDefinition::Record(rec) %}
    {% include "java/Record.java" %}
    {%- when TypeDefinition::Enum(e) %}
    {% include "java/Enum.java" %}
    {%- when TypeDefinition::CallbackInterface(cbi) %}
    {% include "java/CallbackInterface.java" %}
    {% include "java/CallbackInterfaceImpl.java" %}
    {%- endmatch %}
    {% endfor %}

    // ---------------------------------------------------------------
    // Custom exception type
    // ---------------------------------------------------------------

    /**
     * Exception thrown when a native UniFFI call fails.
     */
    public static final class {{ name }}Exception extends RuntimeException {
        public {{ name }}Exception(String message) {
            super(message);
        }
        public {{ name }}Exception(String message, Throwable cause) {
            super(message, cause);
        }
    }
