// Auto-generated by uniffi-bindgen-java-jni. DO NOT EDIT.

package {{ package_name }};

{% for import in imports %}
import {{ import }};
{% endfor %}

/**
 * UniFFI bindings for {{ name }}.
 *
 * Generated from crate: {{ crate_name }}
 */
{% if docstring.is_some() %}
/** {{ docstring.as_ref().unwrap() }} */
{% endif %}
public final class {{ name }} {

    static {
        System.loadLibrary("{{ cdylib_name }}");
    }

    // --- Native method declarations ---
    {% for ffi in ffi_definitions %}
    {%- match ffi %}
    {%- when FfiDefinition::RustFunction(func) %}
    private static native {% match func.return_type %}{% when Some with (ret) %}{{ ret|ffi_type_java }}{% when None %}void{% endmatch %} {{ func.name }}(
        {%- for arg in func.arguments -%}
        {{ arg.ty|ffi_type_java }} {{ arg.name }}{% if !loop.last %}, {% endif %}
        {%- endfor -%}
    );
    {%- when FfiDefinition::CallbackFunction(_cb) %}
    // Callback: {{ _cb.name }}
    {%- endmatch %}
    {% endfor %}

    // --- Top-level functions ---
    {% for func in functions %}
    public static {% match func.return_type %}{% when Some with (ret) %}{{ ret|java_type }}{% when None %}void{% endmatch %} {{ func.java_name }}(
        {%- for arg in func.arguments -%}
        {{ arg.ty|java_type }} {{ arg.java_name }}{% if !loop.last %}, {% endif %}
        {%- endfor -%}
    ) {
        // TODO: call native method and handle lift/lower
    }
    {% endfor %}

    // --- Type definitions ---
    {% for td in type_definitions %}
    {%- match td %}
    {%- when TypeDefinition::Object(obj) %}
    // Object: {{ obj.java_name }}
    {%- when TypeDefinition::Record(rec) %}
    // Record: {{ rec.java_name }}
    {%- when TypeDefinition::Enum(e) %}
    // Enum: {{ e.java_name }}
    {%- when TypeDefinition::CallbackInterface(cbi) %}
    // CallbackInterface: {{ cbi.java_name }}
    {%- endmatch %}
    {% endfor %}
}
